const ADD_VIDEOGAME = 'ADD_VIDEOGAME';
const REMOVE_VIDEOGAME = 'REMOVE_VIDEOGAME';
const ADD_FAVORITE_VIDEOGAME = 'ADD_FAVORITE_VIDEOGAME';
const REMOVE_FAVORITE_VIDEOGAME = 'REMOVE_FAVORITE_VIDEOGAME';
const FILTER_VIDEOGAME = 'FILTER_VIDEOGAME';
const ORDER_VIDEOGAME = 'ORDER_VIDEOGAME';

export {ADD_VIDEOGAME,REMOVE_VIDEOGAME,ADD_FAVORITE_VIDEOGAME,REMOVE_FAVORITE_VIDEOGAME,FILTER_VIDEOGAME,ORDER_VIDEOGAME};